image: archlinux
packages:
  - rustup
tasks:
  - setup_toolchain: |
      rustup toolchain install nightly
      rustup default nightly
      rustup component add rustfmt || true
      rustup component add clippy || true
  - run_checks: |
      cd turbo.fish
      cargo check --verbose
      if ( rustup component list | grep -q rustfmt ); then cargo fmt -- --check; fi
      if ( rustup component list | grep -q clippy ); then cargo clippy -- -A clippy::zero_width_space; fi
